using UnityEngine;
using System.Collections;

namespace GameLogic.AI{
	public enum AIState{
		AI_STATE_NULL,
		AI_STATE_STAND,
		AI_STATE_PATRAL,
		AI_STATE_MOVE,
		AI_STATE_MOVE_X,
		AI_STATE_MOVE_Y,
		AI_STATE_PURSUE,
		AI_STATE_ACTTACK,
		AI_STATE_ACTTACK_CITY,
		AI_STATE_BE_HURT,
		AI_STATE_ESCAPE,
		AI_STATE_WEAK,
		AI_STATE_STONE,
		AI_STATE_DEATH,
		AI_STATE_CHANGE_PET_DOWN,
		AI_STATE_CHANGE_PET_UP,
		AI_STATE_CHANGE_SLEEP,
		AI_STATE_BE_DRAW,
		AI_STATE_DOOR_BREAK,
		AI_STATE_DOOR_NARMOL,
		AI_STATE_BE_COUGHT,
		AI_STATE_AUTO_SKILL,
		AI_STATE_MISPLACE,
		AI_STATE_STATIC_STAND,
		AI_STATE_STATIC_SKILL,
		AI_STATE_PVP_PLAYING,
	}
	
	public enum BulletState{
		
		STATE_BULLET_START,
		STATE_BULLET_MOVE,
		STATE_BULLET_END,
	}
	
	public interface CBassBrian{
		void ThinkAbout();
		void OnMessage();
	}
}
